include ../../../Makeconf

all: bfgsmin.cc bisectionstep.cc celleval.cc finitedifference.cc newtonmin.cc newtonstep.cc numgradient.cc numhessian.cc samin.cc

clean: ; -$(RM) *.o core octave-core *.oct *~
