include ../../../Makeconf

all: bfgsmin.oct bisectionstep.oct celleval.oct finitedifference.oct lbfgsmin.oct newtonstep.oct numgradient.oct numhessian.oct samin.oct

clean: ; -$(RM) *.o core octave-core *.oct *~
