BEGIN {
  print "// DO NOT EDIT -- generated by netcdf_constants.awk";
} 
/\#define[ \t]+NC_[0-9a-zA-Z_]*[ \t]+/ { 
    constant=$2;
    ov = constant;

    if ($0 ~ /.*internally.*/ || constant == "NC_TURN_OFF_LOGGING") {
	next;
    }

    if (constant ~ /NC_.*_BYTE/) {
      ov = "octave_int8(" constant ")";
    }
    else if (constant ~ /NC_.*_UBYTE/) {
      ov = "octave_uint8(" constant ")";
    }
    else if (constant ~ /NC_.*_SHORT/) {
      ov = "octave_int16(" constant ")";
    }
    else if (constant ~ /NC_.*_USHORT/) {
      ov = "octave_uint16(" constant ")";
    }
    else if (constant ~ /NC_.*_INT/) {
      ov = "octave_int32(" constant ")";
    }
    else if (constant ~ /NC_.*_UINT/) {
      ov = "octave_uint32(" constant ")";
    }
    else if (constant ~ /NC_.*_INT64/) {
      ov = "octave_int64(" constant ")";
    }
    else if (constant ~ /NC_.*_UINT64/) {
      ov = "octave_uint64(" constant ")";
    }
    else if (constant ~ /NC_.*_CHAR/) {
      ov = "(char)" constant;
    }
    else if (constant ~ /NC_.*_STRING/) {
      ov = "std::string(" constant ")";
    }
    else if (constant ~ /NC_.*_FLOAT/) {
      ov = "(float)" constant;
    }
    else if (constant ~ /NC_.*_STRING/) {
      ov = "(double)" constant;
    }

    printf "  netcdf_constants[\"%s\"] = octave_value(%s);\n",constant,ov;
}
