#!/bin/sh

netcdf_functions=$(awk -F'[(,]' '/DEFUN_DLD/ { print $2 } ' netcdf_package.cc)

outfile=../PKG_ADD
importfile=../inst/import_netcdf.m

rm -f $outfile $importfile

echo '% File automatically generated by PKG_ADD.sh' > $importfile
echo '% File automatically generated by PKG_ADD.sh' > $outfile

for i in $netcdf_functions; do
    echo ${i#netcdf_}
    cat >> $outfile <<EOF
autoload ("$i", fullfile (fileparts (mfilename ("fullpath")), "netcdf_package.oct"));
EOF
    cat >> $importfile <<EOF
netcdf.${i#netcdf_} = @$i;
EOF

done
