\input texinfo   @c -*-texinfo-*-

@c Copyright (c)  2007  Thomas Treichl <treichl@users.sourceforge.net>
@c odepkg.texi - A package for solving differential equations with Octave
@c
@c Permission is granted to copy, distribute and/or modify this document
@c under the terms of the GNU Free Documentation License, Version 1.2
@c or any later version published by the Free Software Foundation;
@c with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
@c Texts.  A copy of the license is included in the section entitled "GNU
@c Free Documentation License".

@c %*** Start of HEADER
@setfilename odepkg.info
@settitle OdePkg - A package for solving differential equations with Octave
@c %*** End of the HEADER

@c %*** Start of COPYRIGHT
@copying
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled "GNU Free
Documentation License".
@end copying
@c %*** End of COPYRIGHT

@c %*** Start of TITLEPAGE
@titlepage
@title OdePkg
@subtitle A package for solving differential equations with Octave
@author by Thomas Treichl
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@c %*** End of TITLEPAGE

@c %*** Start of BODY
@contents
@ifnottex
@node Top, Beginners's Guide, (dir), (dir)
@top Copyright
@insertcopying
@end ifnottex

@menu
* Beginners's Guide:: Manual for users that are completely new to OdePkg
* User's Guide:: Manual for users that are already familiar with OdePkg
* Coder's Guide:: Manual for users that want to make changes to OdePkg
@end menu

@c %*** Start of first chapter: Beginner's Guide
@node Beginners's Guide, User's Guide, Top, Top
@chapter Beginners's Guide
The ``Beginner's Guide'' is intended for new users who want to solve differential equations with the higher level interpreter language Octave and the toolbox OdePkg. In this chapter it will be explained what OdePkg is about in @ref{About OdePkg} and how OdePkg grew up from the beginning in @ref{OdePkg history and roadmap}. In @ref{Installation and deinstallation} it is explained how OdePkg can be installed and in @ref{First tests and demos} the first examples are explained.

@menu
* About OdePkg:: An introduction about OdePkg
* OdePkg history and roadmap:: From the initial release until now 
* Installation and deinstallation:: Setting up OdePkg on your system
* Reporting Bugs:: Writing about comments and bugs
* First tests and demos:: The --foo-- example and others
@end menu

@node About OdePkg, OdePkg history and roadmap, Beginners's Guide, Beginners's Guide
@section About OdePkg
OdePkg is part of the @b{GNU Octave Repository} (resp. the Octave--Forge project was initiated by Paul Kienzle in 2000) that is hosted at @url{http://octave.sourceforge.net}. The package includes commands for setting up various options, output functions etc. before solving a set of differential equations with the solver functions that are also included. OdePkg formerly was initiated to solve explicitly formulated ordinary differential equations (ODEs) only, but there are already improvements so that differential algebraic equations (DAEs) in explicit form can also be solved. At this time OdePkg is under development with the main target, to make a package that is mostly compatible to the solver functions of the commercial Octave clone.

@node OdePkg history and roadmap, Installation and deinstallation, About OdePkg, Beginners's Guide
@section OdePkg history and roadmap
@cindex history
@cindex roadmap

@multitable @columnfractions .25 .75
@item OdePkg Version 0.0.1
@tab The initial release was already a modification of the old ``ode package'' that was hosted at Octave--Forge and that was written by Marc Compere somewhen between 2000 and 2001. The four variable step--size Runge--Kutta algorithms in three solver files and the three fixed step--size solvers have been merged. It was possible to set some options for these solvers. The four output--functions (@command{odeprint}, @command{odeplot}, @command{odephas2} and @command{odephas3}) have been added along with other examples that initialy have not been there.
@item OdePkg Version 0.1.x
@tab The major milestone along versions 0.1.x was that four stable solvers have been implemented (ie. @command{ode23}, @command{ode45}, @command{ode54} and @command{ode78}) supporting all options that can be set for these kind of solvers and also all necessary functions for setting their options (eg. @command{odeset}, @command{odepkg_structure_check}, etc.). Since version 0.1.3 there is also code available that interfaces the Fortran solver @file{dopri5.f} that is written by Ernst Hairer and Gerhard Wanner (cf. @file{odepkg_mexsolver_dopri5.c} and the helper files @file{odepkgext.c} and @file{odepkgmex.c}).
@item @b{(current)} Version 0.2.x
@tab The main work along version 0.2.x was, to make the interface functions for the non--stiff and stiff solvers from Ernst Hairer and Gerhard Wanner enough stable so that they could be installed by default. Wrapper functions have been added to the package with help texts and tests (namely <TODO>).
@item @b{(future)} Version 0.3.x
@tab All interface functions for the solvers of Hairer and Wanner are stable so that they can be installed by default (via a @file{Makefile} or the @file{PKA_ADD} file). Finished adding all wrapper functions and help descriptions for theses solvers, added tests and demos for these solvers. Ongoing work with this manual.
@item @b{(future)} Version 0.4.x
@tab (Maybe) Some of the Hindmarsh, Brown and Petzold solvers are added, but/and/or I think I prefer the solvers of Jeff Cash instead. Don't know if DDE solver and BVP solvers should be added to this package. By now I don't have the need for this.
@item @b{(future)} Version 0.5.x
@tab (Maybe) A lot of compatibility tests will be done again.
@item @b{(future)} Version 0.6.x
@tab (Maybe) Final release before version 1.0.0.
@item @b{(future)} Version 1.0.0
@tab Completed odepkg release 1.0.0 with m--solvers and mex--solvers.
@end multitable

@node Installation and deinstallation, Reporting Bugs, OdePkg history and roadmap, Beginners's Guide
@section Installation and deinstallation
@cindex installation
@cindex deinstallation

OdePkg can be installed easily using the @command{pkg} command of Octave. Therefore get into the directory where the current release of OdePkg can be found, start @command{octave} and type
@example
pkg install odepkg-x.x.x.tar.gz
@end example
where @file{x.x.x} in the name of the @file{*.tar.gz} file is the current release number that is available. If you want to deinstall resp. remove OdePkg then simply type
@example
pkg uninstall odepkg-x.x.x.tar.gz
@end example
If you encounter problems during the installation process of OdePkg with the @command{pkg} command or if you have an OdePkg that seems to be broken then please report this on the mailing--list of Octave--Forge using the email adress
@ifnothtml
@email{octave-dev@@lists.sourceforge.net}
@end ifnothtml
@ifhtml
@email{octave-dev @{at) lists.sourceforge.net} (replace @{at) with @@)
@end ifhtml 
.

@node Reporting Bugs, First tests and demos, Installation and deinstallation, Beginners's Guide
@section Reporting Bugs
@cindex bugs
If you encounter problems while using OdePkg or if you find bugs in the source codes then please report that via email at the Octave--Forge mailing--list using the email adress 
@ifnothtml
@email{octave-dev@@lists.sourceforge.net}
@end ifnothtml 
@ifhtml
@email{octave-dev @{at) lists.sourceforge.net} (replace @{at) with @@)
@end ifhtml 
and directly send a copy to the email adress 
@ifnothtml
@email{treichl@@users.sourceforge.net}
@end ifnothtml 
@ifhtml
@email{treichl (at@} users.sourceforge.net} (replace (at@} with @@)
@end ifhtml
.

@node First tests and demos,  , Reporting Bugs, Beginners's Guide
@section First tests and demos
@cindex First tests and demos
Let's have a look at the first ordinary differential equation with the name ``foo''. The ``foo'' equation of second order may be of the form @math{y''(t) + C_1 y'(t) + C_2 y(t) = C_3}. With the substitutions @math{y_1(t) = y(t)} and @math{y_2(t) = y'(t)} this differential equation of second order can be split into two differential equations of first order, ie. @math{y'_1(t) = y_2(t)} and @math{y'_2(t) = - C_1 y_2(t) - C_2 y_1(t) + C_3}. Next the numerical values for the constants need to be defined, ie. @math{C_1 = 2.0}, @math{C_2 = 5.0}, @math{C_3 = 10.0}. This set of ordinary differential equations can now be written as an Octave function like
@example
function vdy = foo (vt, vy, varargin)
  vdy(1,1) = vy(2);
  vdy(2,1) = - 2.0 * vy(2) - 5.0 * vy(1) + 10.0;
endfunction
@end example
It is seen that this ODEs do not depend on time, nevertheless the first input argument of this function needs to be defined as the time argument, followed by a integrated state argument @command{vy} and a variable size input argument @command{varargin} that can be used to set up user defined constants or control variables. As it is known that ``foo'' is a set of @slanted{ordinary} differential equations we can choose one of the four m--file Runge--Kutta solvers (cf. @ref{Solver families}). It is also known that the time period of interest may be between @math{t_0=0.0} and @math{t_e = 5.0} as well as that the initial values of the ODEs are @math{y_1(t=0) = 0.0} and @math{y_2(t=0) = 0.0}. Solving this set of ODEs can be done by typing the following commands in the Octave interpreter window
@example
ode45 (@@foo, [0 5], [0 0]);
@end example
A figure window opens and it can be seen how this ODEs are solved from @math{t_0=0.0} to @math{t_e = 5.0}. If opening the figure window is unwanted then output arguments have to be used to catch the results of the solving process, eg.
@example
[t, y] = ode45 (@@foo, [0 5], [0 0]);
@end example
Results can also be obtained as a Octave structure if one output argument is used like in the following example. Then the results are stored in the fields @command{S.x} and @command{S.y}.
@example
S = ode45 (@@foo, [0 5], [0 0]);
@end example
As noticed before, a function for the ordinary differential equations must not be rewritten all the time if some of the parameters are going to change, that's what the input argument @command{varargin} is for. So rewrite the function @command{foo} into @command{newfoo} the following way
@example
function vdy = newfoo (vt, vy, varargin)
  vdy(1,1) = vy(2);
  vdy(2,1) = -varargin@{1@}*vy(2)-varargin@{2@}*vy(1)+varargin@{3@};
endfunction
@end example
There is nothing said about the constant values anymore, but if using the following caller routine in the Octave interpreter window then the same results can be obtained as before (ie. the parameters are directly feed through from the caller routine to the function @command{newfoo}).
@example
ode45 (@@newfoo, [0 5], [0 0], 2.0, 5.0, 10.0);
@end example
The OdePkg can do much more while solving ODEs and DAEs, eg. you can set up other output functions instead of the function @command{odeplot}. So as a last example in this beginning chapter it is shown how this can be done, ie. with the command @command{odeset}
@example
A = odeset ('OutputFcn', @@odeset);
ode45 (@@newfoo, [0 5], [0 0], A, 2.0, 5.0, 10.0);
@end example
The options structure @command{A} that can be set up with with the command @command{odeset} must always be the fourth input argument when using the m--file Runge--Kutta solvers (read the help files for the other solvers if there may be changes). The options that can be set are described in @ref{ODE/DAE options}.

Before you continue reading the next chapter notice that nearly every function that belongs to the OdePkg has its own help describtion and demos, so you can have a look for yourself how the different functions can be used. If you want to have a look at the help describition then type
@example
help fcnname
@end example
in the Octave interpreter window where @command{fcnname} is the name of the function for the help describtion to be viewed. Type
@example
demo fcnname
@end example
in the Octave interpreter window where @command{fcnname} is the name of the function of the demo to run.

@c %*** End of first chapter: Beginner's Guide

@c %*** Start of second chapter: User's Guide
@node User's Guide, Coder's Guide, Beginners's Guide, Top
@chapter User's Guide
@cindex User's Guide
The ``User's Guide'' is intended for users who already do know in principal how to solve differential equations with the higher level language Octave and OdePkg. In this chapter it will be explained which solvers can be used for the different kind of problems in @ref{Solver families} and which options can be set for the optimisation of the solving process in @ref{ODE/DAE options}.

@node Solver families, ODE/DAE options, User's Guide, User's Guide
@section Solver families
@cindex Solver

@menu
* M--file Runge--Kutta solvers::  
* Mex--file Hairer--Wanner solvers::  
* Other solvers::               
@end menu

@node M--file Runge--Kutta solvers, Mex--file Hairer--Wanner solvers, Solver families, Solver families
@subsection M--file Runge--Kutta solvers
The m--file Runge--Kutta solvers are written in the Octave interpreter language and ...

@node Mex--file Hairer--Wanner solvers, Other solvers, M--file Runge--Kutta solvers, Solver families
@subsection Mex--file Hairer--Wanner solvers

Interface functions for the solvers from Ernst Hairer and Gerhard Wanner (hosted at @url{http://www.unige.ch/~hairer}) have been added to the OdePkg as a compressed file with the name @file{hairer.tgz}. The licence of these solvers is a modified BSD license (without advertising clause) and can be found as @file{licence.txt} file in the @file{hairer.tgz} package. Therefore the Fortran files are GPL compatible.

@node Other solvers,  , Mex--file Hairer--Wanner solvers, Solver families
@subsection Other solvers
@c The solvers from Jeff Cash http://www.ma.ic.ac.uk/~jcash have not been added to the OdePkg because it seems that there may exist some unfixed bugs. Modified solver files with bugfixes can be found at http://pitagora.dm.uniba.it/~testset, but the disclaimer's part of this site is not clear and maybe the modified solver files are not GPL compatible.

@c The people from the University of Bari at http://pitagora.dm.uniba.it/~testset have been created the solvers BIMD and GAMD. But like before the disclaimer's part of this internet site is not clear and maybe is not GPL compatible.

@c The OdePack solvers from http://www.netlib.org/odepack have not been added to OdePkg, because the question is not answered if they are really needed from somebody. Other solvers from http://www.netlib.org/ode have not been added because of the same reason.

@node ODE/DAE options,  , Solver families, User's Guide
@section ODE/DAE options
@cindex ODE/DAE options
The default values of odeset can be displayed if odeset is called without any input argument and one output argument argument, eg. the following way
@example
A = odeset ();
disp (A);
@end example

@table @samp
@item RelTol
The option @option{RelTol} is used to set the relative error tolerance for the error estimation of the solver while solving. It can either be a positive scalar or a vector with every element of the vector being a positive scalar (this depends on the solver that is used). The definite error estimation equation also depends on the solver that is used, but generalised it may be of the form @math{e(t) = max (RelTol^T y(t), AbsTol)}. Run
@example
A = odeset ('RelTol', 1, 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], A);
B = odeset ('RelTol', 1e-10, 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], B);
@end example
to see the effect of using different values for the option @option{RelTol}.

@item AbsTol
The option @option{AbsTol} is used to set the absolute error tolerance for the error estimation of the solver while solving. It can either be a positive scalar or a vector with every element of the vector being a positive scalar (this depends on the solver that is used). The definite error estimation equation also depends on the solver that is used, but generalised it may be of the form @math{e(t) = max (RelTol^T y(t), AbsTol)}. Run
@example
A = odeset ('AbsTol', 1e-3, 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], A);
B = odeset ('AbsTol', 1e-10, 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], B);
@end example
to see the effect of using different values for the option @option{AbsTol}.

@item NormControl
The option @option{NormControl} is used to set the type of error tolerance calculation of the solver while solving. It can either be the string @command{'on'} or @command{'off'}. At the time the solver starts the initialisation procedure a warning message may be displayed if the solver will ignore the @command{'on'} setting of this option because of an unhandled resp. missing implementation. The definite error estimation equation if set @command{'on'} also depends on the solver that is used, but generalised it may be of the form @math{e(t) = max (RelTol^T max ( norm (y(t), Inf)), AbsTol)}. Run
@example
A = odeset ('NormControl', 'on', 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], A);
B = odeset ('NormControl', 'off', 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], B);
@end example
to see the effect of using different values for the option @option{NormControl}.

@item MaxStep
The option @option{MaxStep} is used to set the maximum step size for the solver that is used while solving. It can only be a positive scalar. By default this value is set internally by every solver and also may be different when using different solvers. Run
@example
A = odeset ('MaxStep', 10, 'OutputFcn', @@odeprint);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], A);
B = odeset ('MaxStep', 1e-1, 'OutputFcn', @@odeprint);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], B);
@end example
to see the effect of using different values for the option @option{MaxStep}.

@item InitialStep
The option @option{InitialStep} is used to set the initial first step size for the solver. It can only be a positive scalar. By default this value is set internally by every solver and also may be different when using different solvers. Run
@example
A = odeset ('InitialStep', 1, 'OutputFcn', @@odeprint);
ode78 (@@odepkg_equations_vanderpol, [0 1], [2 0], A);
B = odeset ('InitialStep', 1e-5, 'OutputFcn', @@odeprint);
ode78 (@@odepkg_equations_vanderpol, [0 1], [2 0], B);
@end example
to see the effect of using different values for the option @option{InitialStep}.

@item InitialSlope
The option @option{InitialSlope} is not handled by any of the solvers by now.

@item OutputFcn
The option @option{OutputFcn} can be used to set up an output function for displaying the results of the solver while solving. It must be a function handle to a valid function. There are four predefined output functions available with OdePkg. @command{odeprint} prints the actual time values and results in the octave window while solving, @command{odeplot} plots the results over time in a new figure window while solving, @command{odephas2} plots the first result over the second result as a two--dimensional plot while solving and @command{odephas3} plots the first result over the second result over the third result as a three--dimensional plot while solving. Run
@example
A = odeset ('OutputFcn', @@odeprint);
ode78 (@@odepkg_equations_vanderpol, [0 2], [2 0], A);
@end example
to see the effect of using an output function with the option @option{OutputFcn}. User defined output functions can also be used. A typical framework for a self--made output function may then be of the form
@example
function [vret] = odeoutput (vt, vy, vdeci, varargin)
  switch vdeci
    case 'init'
      ## Do everything needed to intialize output function
    case 'calc'
      ## Do everything needed to create output
    case 'done'
      ## Do everything needed to clean up output function
  endswitch
endfunction
@end example
The output function @command{odeplot} is also set automatically if the solver calculation routine is called without any output argument. Run
@example
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0]);
@end example
to see an example.

@item Refine
The option @option{Refine} is used to set the interpolation factor that is used to increase the quality for the output values if an output function is also set with the option @option{OutputFcn}. It can only be a integer value @math{0<=Refine<=5}. Run
@example
A = odeset ('Refine', 0, 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], A);
B = odeset ('Refine', 3, 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], B);
@end example
to see the effect of using different values for the option @option{Refine}.

@item OutputSel
The option @option{OutputSel} is used to set the componentes for which output has to be performed if an output function is also set with the option @option{OutputFcn}. It can only be a vector of integer values. Run
@example
A = odeset ('OutputSel', [1, 2], 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], A);
B = odeset ('OutputSel', [2], 'OutputFcn', @@odeplot);
ode78 (@@odepkg_equations_vanderpol, [0 20], [2 0], B);
@end example
to see the effect of using different values for the option @option{OutputSel}.

@item Stats
The option @option{Stats} is used to print cost statistics about the solving process after solving has been finished. It can either be the string @command{'on'} or @command{'off'}. Run
@example
A = odeset ('Stats', 'off');
[a, b] = ode78 (@@odepkg_equations_vanderpol, [0 2], [2 0], A);
B = odeset ('Stats', 'on');
[c, d] = ode78 (@@odepkg_equations_vanderpol, [0 2], [2 0], B);
@end example
to see the effect of using different values for the option @option{Stats}. The cost statistics cn also be obtained if the solver calculation routine is called with one output argument. The cost statistics then are in the output structure in field @option{stats}. Run
@example
A = odeset ('Stats', 'on');
B = ode78 (@@odepkg_equations_vanderpol, [0 2], [2 0], A);
disp (B);
@end example
to see an example.

@item Jacobian
The option @option{Jacobian} can be used to set up an external Jacobian function or Jacobian matrix for DAE solvers to achieve faster and better results (ODE Runge--Kutta solvers do not need to handle a Jacobian function handle or Jacobian matrix). It must either be a function handle to a valid function or a full constant matrix of size squared the dimension of the set of differential equations. Run
@example
function vdy = fpol (vt, vy, varargin)
  vdy = [vy(2); (1 - vy(1)^2) * vy(2) - vy(1)];
endfunction

function vr = fjac (vt, vy, varargin)
  vr = [0, 1; ...
        -1-2*vy(1)*vy(2), 1-vy(1)^2];
endfunction

A = odeset ('Stats', 'on');
B = odepkg_mexsolver_radau (@@fpol, [0 20], [2 0], A);
C = odeset ('Jacobian', @@fjac, 'Stats', 'on');
D = odepkg_mexsolver_radau (@@fpol, [0 20], [2 0], C);
@end example
to see the effect of using an Jacobian function with the option @option{Jacobian}. User defined Jacobian functions must have the form as described before (ie. @samp{function vr = fjac (vt, vy, varargin)}.

@item JPattern
The option @option{JPattern} is not handled by any of the solvers by now.

@item Vectorized
The option @option{Vectorized} is not handled by any of the solvers by now.

@item Mass 
The option @option{Mass} can be used to set up an external Mass function or Mass matrix for solving DAE problems. It depends on the solver that is used if @option{Mass} is supported or not. It must either be a function handle to a valid function or a full constant matrix of size squared the dimension of the set of differential equations. Run
@example
function vdy = frob (t, y, varargin)
  vdy(1,1) = -0.04*y(1)+1e4*y(2)*y(3);
  vdy(2,1) =  0.04*y(1)-1e4*y(2)*y(3)-3e7*y(2)^2;
  vdy(3,1) =  y(1)+y(2)+y(3)-1;
endfunction

function vmas = fmas (vt, vy, varargin)
  vmas =  [1, 0, 0; 0, 1, 0; 0, 0, 0];
endfunction

A = odeset ('Mass', @@fmas);
B = oderd (@@frob, [0 1e8], [1 0 0], A);
@end example
to see the effect of using a Mass function with the option @option{Mass}. User defined Mass functions must have the form as described before (ie. @samp{function vmas = fmas (vt, vy, varargin)}.

@item MStateDependence
The option @option{MStateDependence} can be used to set up the type of the external Mass function for solving DAE problems if a Mass function handle is set with the option @option{Mass}. It depends on the solver that is used if @option{MStateDependence} is supported or not. It must be a string of the form @command{'none'}, @command{'weak'} or @command{'strong'}. Run
@example
function vdy = frob (vt, vy, varargin)
  vdy(1,1) = -0.04*vy(1)+1e4*vy(2)*vy(3);
  vdy(2,1) =  0.04*vy(1)-1e4*vy(2)*vy(3)-3e7*vy(2)^2;
  vdy(3,1) =  vy(1)+vy(2)+vy(3)-1;
endfunction

function vmas = fmas (vt, varargin)
  vmas =  [1, 0, 0; 0, 1, 0; 0, 0, 0];
endfunction

A = odeset ('Mass', @@fmas, 'MStateDependence', 'none');
B = oderd (@@frob, [0 1e8], [1 0 0], A);
@end example
to see the effect of using a Mass function with the option @option{MStateDependence}. User defined Mass functions must have the form as described before (ie. @samp{function vmas = fmas (vt, varargin)} if the option @option{MStateDependence} was set to @command{'none'}, otherwise the user defined Mass function must have the form @samp{function vmas = fmas (vt, vy, varargin)} if the option @option{MStateDependence} was set to either @command{'weak'} or @command{'strong'}.

@item MvPattern
The option @option{MvPattern} is not handled by any of the solvers by now.
 
@item MassSingular
The option @option{MassSingular} is not handled by any of the solvers by now.

@item NonNegative
The option @option{NonNegative} is not handled by any of the solvers by now.

@item Events
The option @option{Events} can be used to set up an Event function, ie. the Event function can be used to find zero crossings in one of the results. It must either be a function handle to a valid function. Run
@example
function vdy = fbal (vt, vy, varargin)
  vdy(1,1) =  vy(2)+3; 
  vdy(2,1) = -9.81; %# m/s²
endfunction

function [veve, vterm, vdir] = feve (vt, vy, varargin)
  veve  = vy(1); %# Which event component should be tread
  vterm =     1; %# Terminate if an event is found
  vdir  =    -1; %# In which direction, -1 for falling
endfunction

A = odeset ('Events', @@feve);
B = ode78 (@@fbal, [0 1.5], [1 3], A);
plot (B.x, B.y(:,1));
@end example
to see the effect of using an Events function with the option @option{Events}.

@item MaxOrder
The option @option{MaxOrder} is not handled by any of the solvers by now.

@item BDF
The option @option{BDF} is not handled by any of the solvers by now.
@end table

@c %*** End of second chapter: User's Guide

@c %*** Start of third chapter: Coder's Guide
@node Coder's Guide,  , User's Guide, Top
@chapter Coder's Guide
@cindex Coder's Guide

@section C Mex Function Reference
@cindex C Mex Function Reference
@include odepkgmex.texi

@c %*** End of second chapter: Coder's Guide

@c @node Appendix, Index, Coder's Guide, Top
@c @appendix Appendix
@c @include fdl.texi

@c @node Index, C Mex Function Index, Coder's Guide, Top
@c @unnumbered Index
@c @printindex cp

@c @node C Mex Function Index,  , Coder's Guide, Top
@c @unnumbered C Mex Function Index
@c @printindex fn

@bye

@c Local Variables: 
@c mode: texinfo
@c TeX-master: "odepkg"
@c End: 
