#!/bin/sh

# build_atlas_dll
# Support tool to build ATLAS-based BLAS/LAPACK DLL's. This script
# requires various things installed in directories following a
# UNIX-like structure (this script is expected to be installed into
# <prefix>/bin directort):
#	- cc-msvc (<prefix>/bin)
#	- F77 LAPACK library compiled into a static library
#	  named liblapack_f77.lib (<prefix>/lib)
#	- atl_blas.def and lapack.def (<prefix>/lib)
#
# Copyright (C) 2006 Michael Goffioul
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

topdir=`dirname "$0" | sed -e 's,/bin,,'`
case `uname -s` in
  CYGWIN*)
    topdir=`cygpath -m "$topdir"`
    ;;
  MINGW*)
    topdir=`cd "$topdir" && pwd -W`
    ;;
esac

echo "Generating BLAS DLL..."
cc-msvc -shared -o blas.dll -Wl,-def:$topdir/lib/atl_blas.def libatlas.lib libf77blas.lib libcblas.lib -lf2c
if test -f "blas.exp"; then
  rm -f blas.exp
fi

echo "Copying original F77 lapack..."
cp $topdir/lib/liblapack_f77.lib .

echo "Extracting object files from LAPACK/ATLAS..."
for f in `lib -nologo -list liblapack.lib | sed -e 's,\\r,,'`; do
  echo "  -> $f"
  lib -nologo -extract:$f liblapack.lib
done

echo "Merging object files in LAPACK/F77..."
lib -nologo liblapack_f77.lib *.o

echo "Generating LAPACK DLL..."
cc-msvc -shared -o lapack.dll -Wl,-def:$topdir/lib/lapack.def liblapack_f77.lib blas.lib -lf2c
if test -f "lapack.exp"; then
  rm -f lapack.exp
fi

echo "Cleaning..."
rm -f *.o
rm -f liblapack_f77.lib
