include ../../Makeconf

all: lp.oct leval.oct bfgsmin.oct lbfgsmin.oct bisectionstep.oct celleval.oct finitedifference.oct newtonstep.oct numgradient.oct numhessian.oct samin.oct

clean:
	-$(RM) *.o core octave-core *.oct *~
