#!/usr/bin/perl
## Copyright (C) 2011 Carnë Draug <carandraug+dev@gmail.com>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
 
use 5.010;                      # Use Perl 5.10
use strict;                     # Enforce some good programming rules
use warnings;                   # Replacement for the -w flag, but lexically scoped
use File::Find;                 # Load functions to traverse a directory tree
use Tie::File;
use Fcntl;
 
my $old_header = shift;
my $new_header = shift;
 
tie (my @old, "Tie::File", $old_header) or die "Can't tie to '$old_header': $!\n";
tie (my @new, "Tie::File", $new_header) or die "Can't tie to '$new_header': $!\n";
 
sub prepend {
  my $path = $File::Find::name;
  return if $_ =~ m/^\.\.?$/;
  return if $File::Find::dir =~ m/\.svn$/;
  if (-f $_){
    tie (my@file, "Tie::File", $_) or (warn "Can't tie to '$path' : $!\n" && return);
    shift @file for (0 .. $#old);
    unshift (@file, @new);
  }
}
find(\&prepend, @ARGV);
