#!/bin/sh
file=$1
cat <<EOF | octave -q

fid=fopen("$file","rt");
text=setstr(fread(fid,Inf,'uchar')');
fclose(fid);

section = [find(text == setstr(31)), length(text)+1];
line = find(text == "\n");
for idx=1:length(section)-1
   lineend = min(line(line>section(idx)));
   name = text(section(idx)+1:lineend-1);
   body = text(lineend+1:section(idx+1)-1);

   fid = fopen(name,"wt");
   fwrite(fid, body, 'uchar');
   fclose(fid);
end
   
