./"  This is the Unix manual page for mex, written in nroff, the standard
./"  manual formatter for Unix systems.  To format it, type
./"
./"  nroff -man mex.man
./"
./"  This will print a formatted copy to standard output.  If you want
./"  to ensure that the output is plain ASCII, free of any control
./"  characters that nroff uses for underlining etc, pipe the output
./"  through "col -b":
./"
./"  nroff -man mex.man | col -b
./"
./"  Warning: a leading quote "'" or dot "." will not format correctly
./"
./"  I hereby grant this work to the public domain.
./"
.TH mex 1 "September 20, 2001"
.SH NAME
mex \- compile mex file for Octave
.SH SYNOPSIS
.nf
mex [options] mex-file [sources] [objects] [libraries]
.fi
.SH OPTIONS
See mkoctfile for a complete list of options to mex.  
.SH DESCRIPTION
mex compiles a file which calls mex functions into an oct-file.  It
accepts both FORTRAN and C mex-files.  You may include other source
files and object files and libraries in your mex command and they 
will be compiled and linked together into the same oct-file, but the
mex-file must be the first file listed.  See mkoctfile for details.
.SH BUGS
If you want to use the V4 mex interface, use -DV4 on the command 
line instead of -V4.
.SH AUTHOR
.nf
Paul Kienzle
<pkienzle@users.sf.net>
.fi
