sinclude ../../Makeconf
sinclude ../../pkg.mk

PKG_FILES = $(patsubst %,tk_octave/%, COPYING DESCRIPTION INDEX PKG_ADD \
	$(wildcard doc/*) $(wildcard example/*) $(wildcard inst/*) \
	$(wildcard src/*))
