## Copyright (C) 2007 Python Code Generator 
##
## -- WARNING -- Autogenerated  - DONOT EDIT -
##
## This code is released under GPL
## You should have received a copy of the GNU General Public License
## along with Octave; see the file COPYING.  If not, write to the Free
## Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
## 02110-1301, USA.

## -*- texinfo -*-
## @deftypefn {Function File} [@var{Val},@var{unit},@var{uncertanity}] {} BOHR_MAGNETON_IN_INVERSE_METERS_PER_TESLA() 
## Returns the Bohr magneton in inverse meters per tesla
## . Val=466864507  Units=m^-1 T^-1 Uncertanity=0.0000040. 
## @var{Val} is actual value of the constant.
## @var{Unit} is a Units string.
## @var{uncertanity} is +/- value to constant.
##
## Autogenerated on Sat Feb 10 02:48:24 2007
## from NIST database at  http://physics.nist.gov/constants 
## @end deftypefn

## Fundamental Physical Constants --- Complete Listing
## From:  http://physics.nist.gov/constants
## Source: Peter J. Mohr and Barry N. Taylor, CODATA Recommended Values of the 
## Fundamental Physical Constants: 2002, published in Rev. Mod. Phys.
## vol. 77(1) 1-107 (2005).
## Taken from: physics.nist.gov/cuu/Constants/Table/allascii.txt
##
    
function [Val,Unit,Uncertanity]=BOHR_MAGNETON_IN_INVERSE_METERS_PER_TESLA()
	 Val = 466864507; 
	 Units = "m^-1 T^-1";
	 Uncertanity = 0.0000040;
endfunction
%
%!assert(BOHR_MAGNETON_IN_INVERSE_METERS_PER_TESLA,466864507,eps)
%
