## Copyright (C) 2007 Python Code Generator 
##
## -- WARNING -- Autogenerated  - DONOT EDIT -
##
## This code is released under GPL
## You should have received a copy of the GNU General Public License
## along with Octave; see the file COPYING.  If not, write to the Free
## Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
## 02110-1301, USA.

## -*- texinfo -*-
## @deftypefn {Function File} [@var{Val},@var{unit},@var{uncertanity}] {} NEWTONIAN_CONSTANT_OF_GRAVITATION() 
## Returns the Newtonian constant of gravitation
## . Val=66742e-11  Units=m^3 kg^-1 s^-2 Uncertanity=0.0010e-11. 
## @var{Val} is actual value of the constant.
## @var{Unit} is a Units string.
## @var{uncertanity} is +/- value to constant.
##
## Autogenerated on Sat Feb 10 02:48:24 2007
## from NIST database at  http://physics.nist.gov/constants 
## @end deftypefn

## Fundamental Physical Constants --- Complete Listing
## From:  http://physics.nist.gov/constants
## Source: Peter J. Mohr and Barry N. Taylor, CODATA Recommended Values of the 
## Fundamental Physical Constants: 2002, published in Rev. Mod. Phys.
## vol. 77(1) 1-107 (2005).
## Taken from: physics.nist.gov/cuu/Constants/Table/allascii.txt
##
    
function [Val,Unit,Uncertanity]=NEWTONIAN_CONSTANT_OF_GRAVITATION()
	 Val = 66742e-11; 
	 Units = "m^3 kg^-1 s^-2";
	 Uncertanity = 0.0010e-11;
endfunction
%
%!assert(NEWTONIAN_CONSTANT_OF_GRAVITATION,66742e-11,eps)
%
