## Copyright (C) 2007 Python Code Generator 
##
## -- WARNING -- Autogenerated  - DONOT EDIT -
##
## This code is released under GPL
## You should have received a copy of the GNU General Public License
## along with Octave; see the file COPYING.  If not, write to the Free
## Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
## 02110-1301, USA.

## -*- texinfo -*-
## @deftypefn {Function File} [@var{Val},@var{unit},@var{uncertanity}] {} PLANCK_CONSTANT_BY_2_PI_TIMES_C_IN_MEV_FM() 
## Returns the Planck constant over 2 pi times c in MeV fm
## . Val=197326968  Units=MeV fm Uncertanity=0.000017. 
## @var{Val} is actual value of the constant.
## @var{Unit} is a Units string.
## @var{uncertanity} is +/- value to constant.
##
## Autogenerated on Sat Feb 10 02:48:24 2007
## from NIST database at  http://physics.nist.gov/constants 
## @end deftypefn

## Fundamental Physical Constants --- Complete Listing
## From:  http://physics.nist.gov/constants
## Source: Peter J. Mohr and Barry N. Taylor, CODATA Recommended Values of the 
## Fundamental Physical Constants: 2002, published in Rev. Mod. Phys.
## vol. 77(1) 1-107 (2005).
## Taken from: physics.nist.gov/cuu/Constants/Table/allascii.txt
##
    
function [Val,Unit,Uncertanity]=PLANCK_CONSTANT_BY_2_PI_TIMES_C_IN_MEV_FM()
	 Val = 197326968; 
	 Units = "MeV fm";
	 Uncertanity = 0.000017;
endfunction
%
%!assert(PLANCK_CONSTANT_BY_2_PI_TIMES_C_IN_MEV_FM,197326968,eps)
%
